### ISSUE TITLE
[Question] What is the small icon on the bottom right for?

### ISSUE THREAD

**Issue by AnotherUser97** [devkitPro/3ds-hbmenu#13] opened 2017-06-07 11:16 UTC
I can see a small "settings" icon in the bottom right of the screen. Nothing happens though when I tap it. Is this intentional or a WIP feature not tested yet?

**Comment by fincs** [comment] 2017-06-07 11:25
Duplicate of #8.

**Closed as completed by fincs** 2017-06-07 11:25 UTC
Labels: duplicate
