### ISSUE TITLE
Port of the Wii Homebrew Launcher Music

### ISSUE THREAD

**Issue by Volti-p** [devkitPro/3ds-hbmenu#54] opened 2018-12-27 07:42 UTC
I have a Idea for the Homebrew Launcher, Maybe we can add the Soundtrack from the Wii Homebrew Launcher for the menu? :D  This would be so awesome. :)

**Comment by david4444** [comment] 2018-12-28 15:56
yes please

**Comment by fincs** [comment] 2018-12-29 16:55
Duplicate of #52.

**Closed as completed by fincs** 2018-12-29 16:55 UTC
